### PR TITLE
Fix Makefile

### PR DESCRIPTION
**Pull request by dbrgn**
- Upgrade arduino-makefile submodule
- Fix makefile (new board tag)
- Include LedControl library directly (otherwise you need to download it via Arduino IDE)

### CODE REVIEW

**Comment by rnestler** [comment]
I prefer to use arduino-builder since the Arduino Makefiles aren't that well maintained and break every now and then.

**Comment by dbrgn** [comment]
> Arduino Makefiles aren't that well maintained

?? https://github.com/sudar/Arduino-Makefile/commits/master

> and break every now and then

You probably mean "you didn't get it to work on your system once"? :stuck_out_tongue: 

arduino-builder is fine (I think that didn't exist a few years ago), but it would be intereresting to find out why the paths were different on your system.

**Comment by rnestler** [comment]
> You probably mean "you didn't get it to work on your system once"? stuck_out_tongue

No I almost always had trouble with it especially with SAMD targets and ended up using either arduino-builder or platformio.

**Comment by dbrgn** [comment]
Ah, I wasn't aware that you used it in the past. Yeah, today I'd probably use platformio.

**Pull request merged**
